#!/bin/sh
# SPDX-License-Identifier: GPL-3.0-only
find "${1:-srcpkgs/}" -iname template -type f | while IFS= read -r file
do
	file="$(echo "$file" | cut -d/ -f2)"
	for t in hostmakedepends makedepends checkdepends depends
	do
		eval $t="\$(xgetdeps $t $file | tr ' ' '\\0' | sort -z | uniq -zd | paste -zsd ' ')"

		if [ "$(eval echo \$$t)" ]
		then
			printf "%s :: %s :: %s\\n" "$file" "$t" "$(eval echo \$$t)" ;
		fi
	done
done
exit 0
