#!/bin/sh
# SPDX-License-Identifier: GPL-3.0-only
find "${1:-srcpkgs/}" -iname template -type f | while IFS= read -r file
do
	file="$(echo "$file" | cut -d/ -f2)"
	for t in hostmakedepends makedepends checkdepends depends
	do
		eval $t="\$(xgetdeps $t $file | tr ' ' '\\n' | sort | uniq -d | paste -sd ' ')"

		[ "$(eval echo \$$t)" ] && printf "%s :: %s :: %s\\n" "$file" "$t" "$(eval echo \$$t)"
	done
done
