#!/bin/sh
# Takes a list of paths and produces definitions for empty
# directories
[ $# -lt 1 ] && exit 1

printf "%s" "make_dirs=\"$1 0755 root root"
[ $# -lt 2 ] && echo \" || echo ""
shift

while [ $# -gt 0 ]
do
	printf "%s" " $1 0755 root root"
	[ $# -lt 2 ] && echo \" || echo ""
	shift
done
