#!/bin/sh
# Takes a list of paths and produces definitions for empty
# directories
set -- $@
[ $# -lt 4 ] && exit 1

printf "%s" "make_dirs=\"$1 $2 $3 $4"
[ $# -lt 5 ] && echo \" || echo ""
shift ; shift ; shift ; shift

while [ $# -gt 3 ]
do
	printf "%s" " $1 $2 $3 $4"
	[ $# -lt 5 ] && echo \" || echo ""
	shift ; shift ; shift ; shift
done
