#!/usr/bin/env bash
# stub functions for the system
vopt_if() {
	# delimitators of the packages
	# / -> delimitates between spaces in a vopt statement
	# example $(vopt_if var pkgs) -> vopt/var/pkgs
	# -------------------------------------------------------------------------
	# | -> delimitates between spaces inside a vopt pkg
	# example $(vopt_if var 'pkg1 pkg2') -> vopt/var/pkg1|pkg2
	# -------------------------------------------------------------------------
	# ' -> delimitates a variable, more specifically a pkg group
	# example $(vopt_if var pkg1) -> vopt/var/'pkg1'
	if [ "$3" ] ; then
		printf "vopt/%s/'%s'/'%s'>\\n" "$1" "${2// /|}" "${3// /|}"
	else
		printf "vopt/%s/'%s'>\\n" "$1" "${2// /|}"
	fi
}

get_deps() {
	# we need to use bash otherwise templates that have functions that do not
	# conform to POSIX like libmarco-devel_package() will cause problems
	source "$(xdistdir)"/srcpkgs/"$2"/template 2>/dev/null
	eval "ARG=\$$1"
	for pkg in $ARG ; do
		pkg=${pkg//virtual}
		printf "%s " "$pkg"
	done
	printf "\\n"
}

get_deps "${1:?'no dependency type provided'}" "${2:?'no package provided'}"
