#!/usr/bin/env bash
# xgetdeps deptype PKG - get dependencies from package by sourcing it's template
get_deps() {
	# we need to use bash otherwise templates that have functions that do not
	# conform to POSIX like libmarco-devel_package() will cause problems
	source "$(xdistdir)"/srcpkgs/"$2"/template 2>/dev/null
	eval "ARG=\$$1"
	for pkg in $ARG ; do
		printf "%s " "$pkg"
	done
	printf "\\n"
}

get_deps "${1:?'no dependency type provided'}" "${2:?'no package provided'}"
