#!/usr/bin/env bash
# stub functions for the system
vopt_if() {
	if [ "$3" ] ; then
		printf "vopt_%s_%s_%s\\n" "$1" "$2" "$3"
	else
		printf "vopt_%s_%s\\n" "$1" "$2"
	fi
}

get_deps() {
	# we need to use bash otherwise templates that have functions that do not
	# conform to POSIX like libmarco-devel_package() will cause problems
	source "$(xdistdir)"/srcpkgs/"$2"/template 2>/dev/null
	eval "ARG=\$$1"
	for pkg in $ARG ; do
		pkg=${pkg//virtual}
		printf "%s " "$pkg"
	done
	printf "\\n"
}

get_deps "${1:?'no dependency type provided'}" "${2:?'no package provided'}"
