#!/usr/bin/env python3

import argparse
import subprocess
import os.path
import sys
import re
from typing import List


def place_in_file(libpkgname: str, pkglist: List[str], filepath: str):
    template_file: List[str] = []
    hasdevel: bool = False

    with open(filepath, 'r') as file_in:
        for line in file_in:
            if re.search('-devel_package()', line):
                hasdevel = True
                for pkgl in pkglist:
                    template_file.append(pkgl)
                template_file.append('')
            template_file.append(line.strip('\n'))

        if not hasdevel:
            for pkgl in pkglist:
                template_file.append(pkgl)

    with open(filepath, 'w') as file_out:
        file_out.write('\n'.join(template_file))


def main():
    p = argparse.ArgumentParser(description="create libpkg packages.")
    p.add_argument('libpkgname', metavar='libpkgname', type=str,
                   help='name of the lib packages by whitespace')
    p.add_argument('pkgname', metavar='pkgname', type=str,
                   help='name of the original package')
    p.add_argument('-i', dest='replace', action='store_true', default=False,
                   help='replace dependencies in template')

    args = p.parse_args()

    """
        Create a path by taking xdistdir and add srcpkgs/ the pkgname and
        /template
    """
    filepath: str = 'srcpkgs/' + args.pkgname + '/template'
    xdistdir = subprocess.run('xdistdir', stdout=subprocess.PIPE)
    filepath = xdistdir.stdout.decode('utf-8').replace('\n', '/') + filepath

    if not os.path.isfile(filepath):
        print("Invalid filepath: %s" % filepath)
        sys.exit(2)

    libpkgnames = args.libpkgname.split(' ')

    for libpkgname in libpkgnames:

        pkglist: List[str] = ['']
        pkglist.append('%s_package() {' % libpkgname)

        if len(libpkgnames) > 1:
            libname = re.sub('lib', '', libpkgname)
            libname = re.sub('-[0-9].*', '', libname)
            pkglist.append('\tshort_desc="%s library"' % libname)
        else:
            pkglist.append('\tshort_desc+=" - runtime library"')

        pkglist.append('\tpkg_install() {')

        if len(libpkgnames) > 1:
            pkglist.append('\t\tvmove "/usr/lib/%s*.so.*"' % libpkgname)
        else:
            pkglist.append('\t\tvmove "/usr/lib/*.so.*"')

        pkglist.append('\t}')
        pkglist.append('}')

        if args.replace:
            with open(filepath, 'r') as file_in:
                if file_in.read().find(libpkgname + '_package()') != -1:
                    print('package name %s already taken' % libpkgname)
                    continue

            place_in_file(libpkgname, pkglist, filepath)
        
        print('\n'.join(pkglist))

    if args.replace:
        with open(filepath, 'r') as file_in:
            f = file_in.read()

            if f.find(args.libpkgname) != -1:
                print('package name %s already taken' % args.libpkgname)
                sys.exit(2)

        file_in.close()

    if args.replace:
        with open(filepath, "a") as file_out:
            file_out.close()


if __name__ == "__main__":
    main()
