#!/bin/sh
cmd="xmkdevel.py"
for arg; do
	shift
	[ "$arg" = "-i" ] && cmd="xmkdevel.py -i" && continue
	set -- "$@" "$arg"
done

pkgname="${1:-"$(git rev-parse --abbrev-ref HEAD)"}"
$cmd "${2:-${pkgname}}" "$pkgname"
