#!/bin/sh
# SPDX-License-Identifier: GPL-3.0-only

# xpcfiles PKGS ... - Show all .pc files in a package and it's subpackages
for pkg; do
	for subpkg in $(xsubpkg "$pkg") ; do
		xls "$subpkg" | grep '/usr/\(lib\|share\)/pkgconfig' | sed 's|.*/||g' &
	done
done

wait
