#!/bin/sh
cmd="replace.py"

if [ "$1" = "-i" ]; then
	cmd="replace.py -i"
	shift
elif [ "$2" = "-i" ]; then
	cmd="replace.py -i"
fi

for deptype in hostmakedepends makedepends depends checkdepends; do
	pkgs="$(xmindep $(xgetdeps "$deptype" "${1:-$(git rev-parse --abbrev-ref HEAD)}"))"
	[ -z "$pkgs" ] && continue
	$cmd "${1:-$(git rev-parse --abbrev-ref HEAD)}" "$deptype" "$pkgs"
done
