#!/bin/sh
replace=

if [ "$1" = "-i" ]; then
	replace='-i'
	shift
elif [ "$2" = "-i" ]; then
	replace="-i"
fi

for deptype in hostmakedepends makedepends depends checkdepends; do
	pkgs="$(xmindep $(xgetdeps "$deptype" "${1:-$(git rev-parse --abbrev-ref HEAD)}"))"
	[ -z "$pkgs" ] && continue
	replace.py "${1:-$(git rev-parse --abbrev-ref HEAD)}" "$deptype" "$pkgs" "$replace"
done
